/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Juego.Estado;
import javax.swing.JPanel;

/**
 *
 * @author gediez
 */
public class TableroPuzzle extends JPanel {

    /**
     * Creates new form TableroPuzzle
     */
    public TableroPuzzle() {
        initComponents();
        contarMovimientos = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cuadro1 = new javax.swing.JLabel();
        cuadro13 = new javax.swing.JLabel();
        cuadro7 = new javax.swing.JLabel();
        cuadro8 = new javax.swing.JLabel();
        cuadro12 = new javax.swing.JLabel();
        cuadro9 = new javax.swing.JLabel();
        cuadro15 = new javax.swing.JLabel();
        cuadro14 = new javax.swing.JLabel();
        cuadro16 = new javax.swing.JLabel();
        cuadro10 = new javax.swing.JLabel();
        cuadro11 = new javax.swing.JLabel();
        cuadro2 = new javax.swing.JLabel();
        cuadro6 = new javax.swing.JLabel();
        cuadro3 = new javax.swing.JLabel();
        cuadro4 = new javax.swing.JLabel();
        cuadro5 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel2.setText("jLabel2");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel3.setText("jLabel3");

        jLabel16.setText("jLabel16");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuadro1.setBackground(new java.awt.Color(153, 153, 153));
        cuadro1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro1.setText("  ");
        cuadro1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro1.setOpaque(true);
        cuadro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro1MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 60));

        cuadro13.setBackground(new java.awt.Color(153, 153, 153));
        cuadro13.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        cuadro13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro13.setText("1");
        cuadro13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro13.setOpaque(true);
        cuadro13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro13MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, 60));

        cuadro7.setBackground(new java.awt.Color(153, 153, 153));
        cuadro7.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro7.setText("2");
        cuadro7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro7.setOpaque(true);
        cuadro7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro7MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 70, 60));

        cuadro8.setBackground(new java.awt.Color(153, 153, 153));
        cuadro8.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        cuadro8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro8.setText("3");
        cuadro8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro8.setOpaque(true);
        cuadro8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro8MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 70, 60));

        cuadro12.setBackground(new java.awt.Color(153, 153, 153));
        cuadro12.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        cuadro12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro12.setText("8");
        cuadro12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro12.setOpaque(true);
        cuadro12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro12MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 70, 60));

        cuadro9.setBackground(new java.awt.Color(153, 153, 153));
        cuadro9.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        cuadro9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro9.setText("4");
        cuadro9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro9.setOpaque(true);
        cuadro9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro9MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 60));

        cuadro15.setBackground(new java.awt.Color(153, 153, 153));
        cuadro15.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro15.setText("6");
        cuadro15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro15.setOpaque(true);
        cuadro15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro15MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 70, 60));

        cuadro14.setBackground(new java.awt.Color(153, 153, 153));
        cuadro14.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro14.setText("7");
        cuadro14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro14.setOpaque(true);
        cuadro14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro14MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 70, 60));

        cuadro16.setBackground(new java.awt.Color(153, 153, 153));
        cuadro16.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro16.setText("5");
        cuadro16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro16.setOpaque(true);
        cuadro16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro16MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 70, 60));

        cuadro10.setBackground(new java.awt.Color(153, 153, 153));
        cuadro10.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro10.setText("9");
        cuadro10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro10.setOpaque(true);
        cuadro10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro10MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 70, 60));

        cuadro11.setBackground(new java.awt.Color(153, 153, 153));
        cuadro11.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro11.setText("10");
        cuadro11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro11.setOpaque(true);
        cuadro11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro11MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 70, 60));

        cuadro2.setBackground(new java.awt.Color(153, 153, 153));
        cuadro2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro2.setText("11");
        cuadro2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro2.setOpaque(true);
        cuadro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro2MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, 60));

        cuadro6.setBackground(new java.awt.Color(153, 153, 153));
        cuadro6.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro6.setText("12");
        cuadro6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro6.setOpaque(true);
        cuadro6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro6MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 70, 60));

        cuadro3.setBackground(new java.awt.Color(153, 153, 153));
        cuadro3.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro3.setText("13");
        cuadro3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro3.setOpaque(true);
        cuadro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro3MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 70, 60));

        cuadro4.setBackground(new java.awt.Color(153, 153, 153));
        cuadro4.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro4.setText("14");
        cuadro4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro4.setOpaque(true);
        cuadro4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro4MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 70, 60));

        cuadro5.setBackground(new java.awt.Color(153, 153, 153));
        cuadro5.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cuadro5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro5.setText("15");
        cuadro5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadro5.setOpaque(true);
        cuadro5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadro5MouseClicked(evt);
            }
        });
        jPanel1.add(cuadro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void cuadro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro1MouseClicked
        // TODO add your handling code here:
        int[] ficha = {0, 0};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro1MouseClicked

    private void cuadro2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro2MouseClicked
        // TODO add your handling code here:
        int[] ficha = {0, 1};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro2MouseClicked

    private void cuadro3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro3MouseClicked
        // TODO add your handling code here:
        int[] ficha = {0, 2};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro3MouseClicked

    private void cuadro4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro4MouseClicked
        // TODO add your handling code here:
        int[] ficha = {0, 3};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro4MouseClicked

    private void cuadro5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro5MouseClicked
        // TODO add your handling code here:
        int[] ficha = {1, 0};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro5MouseClicked

    private void cuadro6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro6MouseClicked
        // TODO add your handling code here:
        int[] ficha = {1, 1};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro6MouseClicked

    private void cuadro7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro7MouseClicked
        // TODO add your handling code here:
        int[] ficha = {1, 2};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro7MouseClicked

    private void cuadro8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro8MouseClicked
        // TODO add your handling code here:
        int[] ficha = {1, 3};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro8MouseClicked

    private void cuadro9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro9MouseClicked
        // TODO add your handling code here:
        int[] ficha = {2, 0};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro9MouseClicked

    private void cuadro10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro10MouseClicked
        // TODO add your handling code here:
        int[] ficha = {2, 1};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro10MouseClicked

    private void cuadro11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro11MouseClicked
        // TODO add your handling code here:
        int[] ficha = {2, 2};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro11MouseClicked

    private void cuadro12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro12MouseClicked
        // TODO add your handling code here:
        int[] ficha = {2, 3};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro12MouseClicked

    private void cuadro13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro13MouseClicked
        // TODO add your handling code here:
        int[] ficha = {3, 0};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro13MouseClicked

    private void cuadro14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro14MouseClicked
        // TODO add your handling code here:
        int[] ficha = {3, 1};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro14MouseClicked

    private void cuadro15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro15MouseClicked
        // TODO add your handling code here:
        int[] ficha = {3, 2};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro15MouseClicked

    private void cuadro16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro16MouseClicked
        // TODO add your handling code here:
        int[] ficha = {3, 3};
        inicial.moverFicha(ficha);
        this.pintarEstado();
        contarMovimientos++;
    }//GEN-LAST:event_cuadro16MouseClicked

    public void pintarEstado(){
        cuadro1.setText(inicial.getPosicion(0, 0).toString());
        cuadro2.setText(inicial.getPosicion(0, 1).toString());
        cuadro3.setText(inicial.getPosicion(0, 2).toString());
        cuadro4.setText(inicial.getPosicion(0, 3).toString());
        cuadro5.setText(inicial.getPosicion(1, 0).toString());
        cuadro6.setText(inicial.getPosicion(1, 1).toString());
        cuadro7.setText(inicial.getPosicion(1, 2).toString());
        cuadro8.setText(inicial.getPosicion(1, 3).toString());
        cuadro9.setText(inicial.getPosicion(2, 0).toString());
        cuadro10.setText(inicial.getPosicion(2, 1).toString());
        cuadro11.setText(inicial.getPosicion(2, 2).toString());
        cuadro12.setText(inicial.getPosicion(2, 3).toString());
        cuadro13.setText(inicial.getPosicion(3, 0).toString());
        cuadro14.setText(inicial.getPosicion(3, 1).toString());
        cuadro15.setText(inicial.getPosicion(3, 2).toString());
        cuadro16.setText(inicial.getPosicion(3, 3).toString());
    }

    public Estado getInicial() {
        return inicial;
    }

    public void setInicial(Estado inicial) {
        this.inicial = inicial;
    }

    public int getContarMovimientos() {
        return contarMovimientos;
    }

    public void setContarMovimientos(int contarMovimientos) {
        this.contarMovimientos = contarMovimientos;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuadro1;
    private javax.swing.JLabel cuadro10;
    private javax.swing.JLabel cuadro11;
    private javax.swing.JLabel cuadro12;
    private javax.swing.JLabel cuadro13;
    private javax.swing.JLabel cuadro14;
    private javax.swing.JLabel cuadro15;
    private javax.swing.JLabel cuadro16;
    private javax.swing.JLabel cuadro2;
    private javax.swing.JLabel cuadro3;
    private javax.swing.JLabel cuadro4;
    private javax.swing.JLabel cuadro5;
    private javax.swing.JLabel cuadro6;
    private javax.swing.JLabel cuadro7;
    private javax.swing.JLabel cuadro8;
    private javax.swing.JLabel cuadro9;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private Estado inicial;
    private int contarMovimientos;
}
